import '@/styles/globals.css'
import Sidebar from '@/components/Sidebar'
import Header from '@/components/Header'
import { QueryClientProvider, QueryClient } from 'react-query'
import { store } from '@/redux/store';
import { Provider } from 'react-redux'
import Head from 'next/head'
import { SessionProvider } from 'next-auth/react';
import { useState } from 'react';

const queryClient = new QueryClient();

export default function App({ Component, pageProps: { session, ...pageProps } }) {


  return (
    <>
      <Head>
        <title>Web Ormawa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='font-poppins'>

          <QueryClientProvider client={queryClient}>
            <SessionProvider session={session}>
              <Provider store={store}>
                <Component {...pageProps}/>
              </Provider>
            </SessionProvider>
          </QueryClientProvider>

      </div>
    </>
  )
}


