import Card from '@/components/Card'
import Title from '@/components/Title'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title
        title={'dashboard'}
      />
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <Card
          title={'tugas selesai'}
          count={'300'}
        />
        <Card
          title={'tugas belum'}
          count={'300'}
        />
        <Card
          title={'tugas proses'}
          count={'300'}
        />
      </div>
    </>
  )
}
